### ISSUE TITLE
Zentrale Extension Basis bereitstellen

### ISSUE THREAD

**Issue by LUDOBF** [ludopus/ludopus-issues#1]
**Story:**
Ich als Dev von Ludopus,
möchte gerne eine Extension für BC/NAV haben, die mir zentrale Funktionen und Pages bereitstellt,
damit ich in allen weiteren Extensions nur darauf referenzieren muss und nicht den Code jedesmal neu implementieren muss.

**Akzeptanzkriterien:**
- Der ID-Bereich liegt in dem von Microsoft vergebenen Bereich.
- Die Extension hat einen entsprechenden Extension-Identifier.
- Die Extension hat eine entschprechende Dokumentation.
- Folgende Funktionen sollten implementiert sein:
  - Es existiert eine Page, Detail-Page, Table für API-Credentials.
    - Das PW wird verschlüsselt gespeichert.
  - API-Requests (GET, POST, PATCH, PUT) können über eine jeweilige Funktion ausgelöst werden.
  - API-Responses werden decodiert.

**Tasks:**
- [x] ludopus/bc-extension-base-app#3
- [x] ludopus/bc-extension-base-app#4
- [x] ludopus/bc-extension-base-app#5
- [x] ludopus/bc-extension-base-app#6
- [x] ludopus/bc-extension-base-app#7
- [x] ludopus/bc-extension-base-app#8
- [x] ludopus/bc-extension-base-app#9
